---
version: '2.4'
#only add core CCD services here. Side services should be added to others.yaml

services:
  ccd-user-profile-api:
    image: "${CCD_USER_PROFILE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/user-profile-api:${CCD_USER_PROFILE_API_TAG:-latest}"
    environment:
      USER_PROFILE_DB_HOST: ccd-shared-database
      USER_PROFILE_DB_PORT: 5432
      USER_PROFILE_DB_USERNAME: "${DB_USERNAME}"
      USER_PROFILE_DB_PASSWORD: "${DB_PASSWORD}"
      USER_PROFILE_DB_USE_SSL: "${DB_USE_SSL}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-user-profile-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 4453:4453
    depends_on:
      - ccd-shared-database
    networks:
      - ccd-network

  ccd-definition-store-api:
    image: "${CCD_DEFINITION_STORE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/definition-store-api:${CCD_DEFINITION_STORE_API_TAG:-latest}"
    environment:
      DEFINITION_STORE_DB_HOST: ccd-shared-database
      DEFINITION_STORE_DB_PORT: 5432
      DEFINITION_STORE_DB_USERNAME: "${DB_USERNAME}"
      DEFINITION_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DEFINITION_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DEFINITION_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      DEFINITION_STORE_S2S_AUTHORISED_SERVICES: ccd_data,ccd_gw,ccd_admin
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-definition-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      ELASTIC_SEARCH_ENABLED: "${ES_ENABLED_DOCKER}"
      ELASTIC_SEARCH_HOST: "ccd-elasticsearch"
      ELASTIC_SEARCH_FAIL_ON_IMPORT: "true"
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      # JAVA_TOOL_OPTIONS: '-XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005'
    ports:
      - 4451:4451
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      # - 5005:5005
    depends_on:
# Uncomment this line to enable ccd test stub service
#     ccd-test-stubs-service:
#       condition: service_started
      idam-api:
        condition: service_started
      ccd-shared-database:
        condition: service_started
      ccd-user-profile-api:
        condition: service_started
    networks:
      - ccd-network

  ccd-data-store-api:
    image: "${CCD_DATA_STORE_API_USE_LOCAL-hmctspublic.azurecr.io/}ccd/data-store-api:${CCD_DATA_STORE_API_TAG:-latest}"
    environment:
      DATA_STORE_DB_HOST: ccd-shared-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DATA_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DATA_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DATA_STORE}"
      DATA_STORE_TOKEN_SECRET: iuasbcuasdcbasdgcasdgcuysachjsacyasdgjcgasdj
      DATA_STORE_S2S_AUTHORISED_SERVICES: ccd_gw,ccd_gateway,fpl_case_service,ccd_data,ccd_ps,aac_manage_case_assignment
      DEFINITION_STORE_HOST: http://ccd-definition-store-api:4451
      USER_PROFILE_HOST: http://ccd-user-profile-api:4453
      IDAM_USER_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ccd-data-store-api
      REFORM_TEAM: ccd
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
      ELASTIC_SEARCH_ENABLED: "${ES_ENABLED_DOCKER}"
      ELASTIC_SEARCH_HOSTS: ccd-elasticsearch:9200
      ELASTIC_SEARCH_DATA_NODES_HOSTS: "http://ccd-elasticsearch:9200"
      CCD_DEFAULTPRINTURL: https://return-case-doc-ccd.nonprod.platform.hmcts.net/jurisdictions/:jid/case-types/:ctid/cases/:cid
      CCD_DM_DOMAIN: "${CCD_DM_DOMAIN}"
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      # JAVA_TOOL_OPTIONS: '-XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005'
    ports:
      - 4452:4452
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      # - 5005:5005
    depends_on:
# Uncomment this line to enable ccd test stub service
#     ccd-test-stubs-service:
#       condition: service_started
      idam-api:
        condition: service_started
      ccd-shared-database:
        condition: service_started
      ccd-user-profile-api:
        condition: service_started
      ccd-definition-store-api:
        condition: service_started
    networks:
      - ccd-network

  service-auth-provider-api:
    image: "hmctspublic.azurecr.io/rpe/service-auth-provider:latest"
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    ports:
      - 4502:8080
    environment:
      SERVER_PORT: 8080
      JWT_KEY: wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      MICROSERVICEKEYS_AAC_MANAGE_CASE_ASSIGNMENT: "${BEFTA_S2S_CLIENT_SECRET_OF_AAC_MANAGE_CASE_ASSIGNMENT}"
      MICROSERVICEKEYS_CCD_DATA: "${IDAM_KEY_CCD_DATA_STORE}"
      MICROSERVICEKEYS_CCD_GW: "${IDAM_KEY_CCD_GATEWAY}"
      MICROSERVICEKEYS_CCD_DEFINITION: "${IDAM_KEY_CCD_DEFINITION_STORE}"
      MICROSERVICEKEYS_CCD_ADMIN: "${IDAM_KEY_CCD_ADMIN}"
      MICROSERVICEKEYS_CCD_PS: "${IDAM_KEY_CCD_PS}"
      MICROSERVICEKEYS_FPL_CASE_SERVICE: "${IDAM_KEY_FPL_CASE_SERVICE}"
      MICROSERVICEKEYS_XUI_WEBAPP: "${BEFTA_S2S_CLIENT_SECRET_OF_XUI_WEBAPP}"
      TESTING_SUPPORT_ENABLED: "true"
    networks:
      - ccd-network

  ccd-shared-database:
    build: ../database
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 10
    environment:
      DB_USERNAME:
      DB_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5050:5432
    volumes:
      - ccd-docker-ccd-shared-database-data:/var/lib/postgresql/data
    networks:
      - ccd-network

  ccd-test-stubs-service:
    image: "${CCD_TEST_STUBS_SERVICE_USE_LOCAL-hmctspublic.azurecr.io/}ccd/test-stubs-service:${CCD_TEST_STUBS_SERVICE_TAG:-latest}"
    environment:
      - WIREMOCK_SERVER_MAPPINGS_PATH=wiremock
    ports:
      - 5555:5555
    networks:
      - ccd-network
    #provide custom Idam roles when using Idam Stub.
    #uncomment and add the desired roles to idam_stub_get_details_custom.json. Then restart the Stub Service
#    volumes:
#      - ${PWD}/resources/idam_stub_get_details_custom.json:/opt/app/wiremock/mappings/idam_get_details.json

volumes:
  ccd-docker-ccd-shared-database-data:
  wiremock:

networks:
  ccd-network:
    external: true
