---
version: '2.4'

services:
  ccd-case-management-web:
    image: "${CCD_CASE_MANAGEMENT_WEB_USE_LOCAL-hmctspublic.azurecr.io/}ccd/case-management-web:${CCD_CASE_MANAGEMENT_WEB_TAG:-latest}"
    container_name: ccd-case-management-web
    environment:
      IDAM_LOGIN_URL: "${IDAM_STUB_LOCALHOST:-http://localhost:3501}/login"
      CCD_GATEWAY_BASE_URL: http://localhost:3453
      CCD_ACTIVITY_BASE_URL:
      DM_GATEWAY_BASE_URL: https://api-gateway.dev.dm.reform.hmcts.net
      OAUTH2_CLIENT_ID: ccd_gateway
    ports:
      - 3451:3451
    depends_on:
      - ccd-api-gateway
    networks:
      - ccd-network

  ccd-admin-web:
    image: "${CCD_CASE_MANAGEMENT_WEB_USE_LOCAL-hmctspublic.azurecr.io/}ccd/case-management-web:${CCD_CASE_MANAGEMENT_WEB_TAG:-latest}"
    container_name: ccd-admin-web
    environment:
      IDAM_BASE_URL: ""
      IDAM_S2S_URL:
      IDAM_ADMIN_WEB_SERVICE_KEY:
      IDAM_LOGOUT_URL:
      IDAM_OAUTH2_TOKEN_ENDPOINT:
      IDAM_OAUTH2_AW_CLIENT_SECRET:
      ADMINWEB_LOGIN_URL:
      ADMINWEB_IMPORT_URL:
      APPINSIGHTS_INSTRUMENTATIONKEY:
    ports:
    - 3100:3100
    depends_on:
    - ccd-api-gateway
    networks:
    - ccd-network

  ccd-api-gateway:
    image: "${CCD_API_GATEWAY_USE_LOCAL-hmctspublic.azurecr.io/}ccd/api-gateway-web:${CCD_API_GATEWAY_TAG:-latest}"
    container_name: ccd-api-gateway-web
    environment:
      IDAM_BASE_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_USER_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_SERVICE_KEY: "${IDAM_KEY_CCD_GATEWAY}"
      IDAM_OAUTH2_LOGOUT_ENDPOINT: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/session/:token"
      IDAM_OAUTH2_CLIENT_ID: ccd_gateway
      IDAM_OAUTH2_CLIENT_SECRET: ccd_gateway_secret
      IDAM_OAUTH2_TOKEN_ENDPOINT: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/oauth2/token"
      ADDRESS_LOOKUP_TOKEN:
      PROXY_AGGREGATED: http://ccd-data-store-api:4452
      PROXY_DATA: http://ccd-data-store-api:4452
      PROXY_DEFINITION_IMPORT: http://ccd-definition-store-api:4451
      PROXY_DEFINITION_DATA: http://ccd-definition-store-api:4451/api/data
      PROXY_DEFINITION_DISPLAY: http://ccd-definition-store-api:4451/api/display
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 3453:3453
    depends_on:
      - ccd-user-profile-api
      - ccd-definition-store-api
      - ccd-data-store-api
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
