---
version: '2.4'

services:
  ccd-admin-web:
    image: "${CCD_ADMIN_WEB_USE_LOCAL-hmctspublic.azurecr.io/}ccd/admin-web:${CCD_ADMIN_WEB_TAG:-latest}"
    container_name: ccd-admin-web
    environment:
      SECURE_AUTH_COOKIE_ENABLED : "false"
      USE_CSRF_PROTECTION : "false"
      SECURITY_REFERRER_POLICY : origin
      IDAM_BASE_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_ADMIN_WEB_SERVICE_KEY: AAAAAAAAAAAAAAAD
      IDAM_LOGOUT_URL: "${IDAM_STUB_LOCALHOST:-http://localhost:3501}/login"
      IDAM_OAUTH2_TOKEN_ENDPOINT: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/oauth2/token"
      IDAM_OAUTH2_LOGOUT_ENDPOINT: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/session/:token"
      IDAM_OAUTH2_AW_CLIENT_SECRET: ccd_admin_secret
      IDAM_SERVICE_NAME: ccd_admin
      IDAM_OAUTH2_CLIENT_ID : ccd_admin
      ADMINWEB_LOGIN_URL: "${IDAM_STUB_LOCALHOST:-http://localhost:3501}/login"
      ADMINWEB_IMPORT_URL: http://docker.for.mac.localhost:4451/import
      ADMINWEB_JURISDICTIONS_URL : http://docker.for.mac.localhost:4451/api/data/jurisdictions
      ADMINWEB_USER_PROFILE_URL : http://docker.for.mac.localhost:4453/users
      ADMINWEB_SAVE_USER_PROFILE_URL : http://docker.for.mac.localhost:4453/users/save
      ADMINWEB_USER_ROLE_URL : http://docker.for.mac.localhost:4451/api/user-role
      ADMIN_ALL_USER_ROLES_URL : http://docker.for.mac.localhost:4451/api/user-roles
      ADMINWEB_CREATE_DEFINITION_URL : http://docker.for.mac.localhost:4451/api/draft
      ADMINWEB_UPDATE_DEFINITION_URL : http://docker.for.mac.localhost:4451/api/draft/save
      ADMINWEB_DELETE_DEFINITION_URL : http://docker.for.mac.localhost:4451/api/draft
      ADMINWEB_DEFINITIONS_URL : http://docker.for.mac.localhost:4451/api/drafts
      ADMINWEB_WHOAMI_URL : http://docker.for.mac.localhost:4451/api/idam/profile
      ADMINWEB_AUTHORIZATION_URL : http://docker.for.mac.localhost:4451/api/idam/adminweb/authorization
      ADMINWEB_IMPORT_AUDITS_URL : http://docker.for.mac.localhost:4451/api/import-audits
      ADMINWEB_ELASTIC_INDEX_URL : http://docker.for.mac.localhost:4451/elastic-support/index
      ADMINWEB_ROLES_WHITELIST : "ccd-import,ccd-import-validate"
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
    - 3100:3100
    depends_on:
    - service-auth-provider-api
    - ccd-definition-store-api
    - ccd-user-profile-api
    networks:
    - ccd-network

  ccd-api-gateway:
    image: "${CCD_API_GATEWAY_USE_LOCAL-hmctspublic.azurecr.io/}ccd/api-gateway-web:${CCD_API_GATEWAY_TAG:-latest}"
    container_name: ccd-api-gateway-web
    environment:
      IDAM_BASE_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_USER_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_S2S_URL: http://service-auth-provider-api:8080
      IDAM_SERVICE_KEY: "${IDAM_KEY_CCD_GATEWAY}"
      IDAM_OAUTH2_LOGOUT_ENDPOINT: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/session/:token"
      IDAM_OAUTH2_CLIENT_ID: ccd_gateway
      IDAM_OAUTH2_CLIENT_SECRET: ccd_gateway_secret
      IDAM_OAUTH2_TOKEN_ENDPOINT: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}/oauth2/token"
      ADDRESS_LOOKUP_TOKEN:
      PROXY_AGGREGATED: http://docker.for.mac.localhost:4452
      PROXY_DATA: http://docker.for.mac.localhost:4452
      PROXY_CASE_ACTIVITY: http://host.docker.internal:3460
      PROXY_PRINT_SERVICE: http://host.docker.internal:3200
      PROXY_PAYMENTS: "${PROXY_PAYMENTS_STUB:-http://localhost:9999/payments}"
      PROXY_DEFINITION_IMPORT: http://docker.for.mac.localhost:4451
      PROXY_DEFINITION_DATA: http://docker.for.mac.localhost:4451/api/data
      PROXY_DEFINITION_DISPLAY: http://docker.for.mac.localhost:4451/api/display
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - 3453:3453
    depends_on:
      - ccd-user-profile-api
      - ccd-definition-store-api
      - ccd-data-store-api
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
