---
version: '2.4'

services:
  hmc-cft-hearing-service:
    image: "${HMC_CFT_HEARING_SERVICE_USE_LOCAL-hmctspublic.azurecr.io/}hmc/cft-hearing-service:${HMC_CFT_HEARING_SERVICE_TAG:-latest}"
    environment:
      # these environment variables are used by java-logging library
      CFT_HEARING_SERVICE_S2S_AUTHORISED_SERVICES: xui_webapp,hmc_hmi_inbound_adapter,sscs,fis_hmc_api
      IDAM_API_BASE_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_OIDC_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_S2S_URL: http://localhost:4502
      IDAM_OAUTH2_DATA_STORE_CLIENT_SECRET: idam_data_store_client_secret
      CFT_HEARING_SERVICE_DB_USERNAME:
      CFT_HEARING_SERVICE_DB_PASSWORD:
      CFT_HEARING_SERVICE_DB_HOST: docker.for.mac.localhost
      CFT_HEARING_SERVICE_DB_PORT: 5050
      CFT_HEARING_SERVICE_DB_NAME:
      DATA_STORE_DB_HOST: ccd-shared-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      DATA_STORE_DB_USE_SSL: "${DB_USE_SSL}"
      DATA_STORE_IDAM_KEY: "${IDAM_KEY_CCD_DATA_STORE}"

      CLIENT_ID: a12e8358-fbd8-4a98-84aa-a106161dfbd7
      FH_BASE_URL: https://login.microsoftonline.com
      FH_GET_TOKEN_URL: /531ff96d-0ae9-462a-8d2d-bec7c0b42082/oauth2/v2.0/token
      GRANT_TYPE: client_credentials
      HMC_SERVICE_BUS_CONNECTION_STRING:
      HMC_OUTBOUND_QUEUE_CONNECTION_STRING:
      HMC_QUEUE_CONNECTION_STRING:
      HMI_BASE_URL: https://hmi-apim.test.platform.hmcts.net/hmi
      HMI_DESTINATION_SYSTEM: MOCK
      HMI_SOURCE_SYSTEM: CFT
      HMC_SERVICE_BUS_QUEUE: mark-inbound
      HMC_SERVICE_BUS_TOPIC: mark-topic
      HMC_OUTBOUND_SERVICE_BUS_QUEUE: mark-outbound
      SCOPE: api://d49d7fa2-6904-4223-a907-3b8992af4190/.default
      SERVICE_AUTH_PROVIDER_API_BASE_URL: http://docker.for.mac.localhost:4502

      ROOT_APPENDER:
      JSON_CONSOLE_PRETTY_PRINT:
      ROOT_LOGGING_LEVEL:
      REFORM_SERVICE_TYPE:
      REFORM_SERVICE_NAME:
      REFORM_TEAM:
      REFORM_ENVIRONMENT:
      LOGBACK_DATE_FORMAT:
      LOGBACK_REQUIRE_THREAD:
      LOGBACK_REQUIRE_ALERT_LEVEL: false
      LOGBACK_REQUIRE_ERROR_CODE: false
      # Uncomment this line to enable JVM debugging and uncomment the port mapping below
      #  JAVA_TOOL_OPTIONS: -XX:InitialRAMPercentage=30.0 -XX:MaxRAMPercentage=65.0 -XX:MinRAMPercentage=30.0 -XX:+UseConcMarkSweepGC -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    ports:
      - 4561:4561
      # Uncomment this and the JAVA_TOOL_OPTIONS flag for JVM debugging
      # - 5005:5005
    depends_on:
      - ccd-data-store-api
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
