version: '2.4'
services:

  ccd-logstash:
    image: "${CCD_LOGSTASH_REPOSITORY_URL:-hmctspublic.azurecr.io}/ccd/logstash:ccd-latest"
    container_name: ccd-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - ccd-network

  divorce-logstash:
    image: "${CCD_LOGSTASH_REPOSITORY_URL:-hmctspublic.azurecr.io}/ccd/logstash:divorce-latest"
    container_name: divorce-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - ccd-network

  sscs-logstash:
    image: "${CCD_LOGSTASH_REPOSITORY_URL:-hmctspublic.azurecr.io}/ccd/logstash:sscs-latest"
    container_name: sscs-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - ccd-network

  ethos-logstash:
    image: "${CCD_LOGSTASH_REPOSITORY_URL:-hmctspublic.azurecr.io}/ccd/logstash:ethos-latest"
    container_name: ethos-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - ccd-network

  cmc-logstash:
    image: "${CCD_LOGSTASH_REPOSITORY_URL:-hmctspublic.azurecr.io}/ccd/logstash:cmc-latest"
    container_name: cmc-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - ccd-network

  probate-logstash:
    image: "${CCD_LOGSTASH_REPOSITORY_URL:-hmctspublic.azurecr.io}/ccd/logstash:probate-latest"
    container_name: probate-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - ccd-network

  testall-logstash:
    image: "${CCD_LOGSTASH_REPOSITORY_URL:-hmctspublic.azurecr.io}/ccd/logstash:testall-latest"
    container_name: testall-logstash
    environment:
      - XPACK_MONITORING_ENABLED=false
      - DB_URL=jdbc:postgresql://ccd-shared-database:5432/ccd_data?stringtype=unspecified&ssl=false
      - DB_USER=ccd
      - DB_PWD=ccd
      - ES_DATA_NODES_URL=http://ccd-elasticsearch:9200
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true

