version: '2.4'
#only add core CCD services here. Side services should be added to others.yaml

services:
  mock-services-api:
    image: rodolpheche/wiremock
    volumes:
      - ./mocks:/home/wiremock:rw
    ports:
      - 8765:8080

networks:
  ccd-network:
    external: true

