version: '2.4'

services:
  ts-translation-service:
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: "${TS_TRANSLATION_SERVICE_USE_LOCAL-hmctspublic.azurecr.io/}ts/translation-service:${TS_TRANSLATION_SERVICE_TAG:-latest}"
    container_name: translation-service
    environment:
      TS_TRANSLATION_SERVICE_DB_HOST: "${CCD_POSTGRES_11:-ccd-shared-database}"
      TS_TRANSLATION_SERVICE_DB_PORT: 5432
      TS_TRANSLATION_SERVICE_DB_NAME: ts_translation_service
      TS_TRANSLATION_SERVICE_DB_USERNAME: ${DB_USERNAME}
      TS_TRANSLATION_SERVICE_DB_PASSWORD: ${DB_PASSWORD}
      IDAM_API_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      IDAM_OIDC_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      TS_TRANSLATION_SERVICE_S2S_AUTHORISED_SERVICES: xui_webapp,ccd_admin
      S2S_URL: http://service-auth-provider-api:8080
      REFORM_SERVICE_NAME: ts-translation-service
      REFORM_TEAM: ts
      REFORM_ENVIRONMENT: local
      APPINSIGHTS_INSTRUMENTATIONKEY: key
    ports:
      - "4650:4650"
    depends_on:
      ccd-shared-database:
        condition: service_started
      # Uncomment this line to enable ccd-shared-database with Postgres version 11
      #ccd-shared-database-v11:
      #  condition: service_started
      service-auth-provider-api:
        condition: service_started
    networks:
      - ccd-network
