input {
    jdbc {
        jdbc_connection_string => "${DATA_STORE_URL}"
        jdbc_user => "${DATA_STORE_USER}"
        jdbc_password => "${DATA_STORE_PASS}"
        jdbc_validate_connection => true
        jdbc_driver_library => "/usr/share/logstash/ccd/postgresql.jar"
        jdbc_driver_class => "org.postgresql.Driver"
        jdbc_default_timezone => "UTC"
        statement => "WITH candidates AS (
      SELECT q.id
      FROM case_data_logstash_queue q
      ORDER BY q.id
      FOR UPDATE SKIP LOCKED
      LIMIT 1000
  )
  DELETE FROM case_data_logstash_queue q
  USING candidates c, case_data cd
  WHERE q.id = c.id
    AND q.case_data_id = cd.id
  RETURNING q.id AS version,
            cd.id,
            created_date,
            last_modified,
            jurisdiction,
            case_type_id,
            state,
            last_state_modified_date,
            data::TEXT AS json_data,
            data_classification::TEXT AS json_data_classification,
            reference,
            security_classification,
            supplementary_data::TEXT AS json_supplementary_data"
        clean_run => false
        schedule => "* * * * * *"
    }
}
